# Generated by Django 3.2.19 on 2023-07-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_the_plate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='body',
        ),
    ]
