# Generated by Django 3.2.19 on 2023-07-24 16:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_the_plate', '0002_rename_comment_text_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetag',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetag',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(related_name='recipes', to='share_the_plate.Category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='share_the_plate.Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='default_profile.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Enter cooking time in minutes'),
        ),
        migrations.DeleteModel(
            name='RecipeCategory',
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
