# Generated by Django 3.2.19 on 2023-07-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_the_plate', '0003_auto_20230724_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
